language: go
go:
 - '1.20'

# From https://github.com/travis-ci/travis-ci/issues/8891#issuecomment-353403729
before_install:
- echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
- sudo service docker restart

install:
- sudo apt-get update && sudo apt-get install -y libpcap-dev
- go get -v -t ./...

before_script:
- go install github.com/mattn/goveralls@latest

script:
- go vet ./...
- go build ./...
- go test ./... -cover=1 -coverprofile=_c.cov
- go test ./... -race
- $GOPATH/bin/goveralls -service=travis-ci -coverprofile=_c.cov
