language: go

before_install:
- echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
- sudo service docker restart

install:
- sudo apt-get update && sudo apt-get install -y libpcap-dev
- go get -v -t ./...

before_script:
- go get github.com/mattn/goveralls

script:
- go vet ./...
- go build ./...
- go test ./... -cover=1 -coverprofile=_c.cov
- $GOPATH/bin/goveralls -service=travis-ci -coverprofile=_c.cov
